DROP TABLE INFYRETAIL_ROLE CASCADE CONSTRAINTS;

DROP TABLE INFYRETAIL_USER CASCADE CONSTRAINTS;

DROP TABLE INFYRETAIL_PRODUCT CASCADE CONSTRAINTS;


DROP SEQUENCE INFYRETAIL_PRODUCT_SEQ;


CREATE SEQUENCE INFYRETAIL_PRODUCT_SEQ START WITH 1004 INCREMENT BY 1;

CREATE TABLE  INFYRETAIL_ROLE 
   (	ROLE_TYPE CHAR(1) NOT NULL ENABLE, 
	ROLE_NAME VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT INFYRETAIL_ROLE_PK PRIMARY KEY (ROLE_TYPE) ENABLE, 
	 CONSTRAINT INFYRETAIL_ROLE_NAME_UN UNIQUE (ROLE_NAME) ENABLE
   );





CREATE TABLE  INFYRETAIL_USER
   (	USER_ID VARCHAR2(50) NOT NULL ENABLE, 
	USER_NAME VARCHAR2(20) NOT NULL ENABLE, 
	USER_ROLE CHAR(1) NOT NULL ENABLE, 
	USER_PASSWORD VARCHAR2(20), 
	USER_EMAIL VARCHAR2(50) NOT NULL ENABLE, 
	USER_MOBILE_NO NUMBER NOT NULL ENABLE, 
	USER_DOB DATE, 
	USER_ADDRESS VARCHAR2(200), 
	USER_GENDER CHAR(1), 
	USER_TYPE VARCHAR2(20),
	USER_STATUS CHAR(1), 
	 CONSTRAINT INFYRETAIL_USER_EMAIL_UN UNIQUE (USER_EMAIL) ENABLE, 
	 CONSTRAINT INFYRETAIL_USER_ID_PK PRIMARY KEY (USER_ID) ENABLE,  
	 CONSTRAINT INFYRETAIL_USER_ROLE_FK FOREIGN KEY (USER_ROLE)
	  REFERENCES  INFYRETAIL_ROLE (ROLE_TYPE) ENABLE
   );

select *from INFYRETAIL_USER

update INFYRETAIL_USER set USER_TYPE='SILVER' where USER_ID='S101'




CREATE TABLE  INFYRETAIL_PRODUCT
   (	PRODUCT_ID NUMBER NOT NULL ENABLE, 
	PRODUCT_NAME VARCHAR2(100) NOT NULL ENABLE, 
	PRODUCT_CATEGORY VARCHAR2(50), 
	PRODUCT_BRAND VARCHAR2(100),
	PRODUCT_COST NUMBER(10,2) NOT NULL ENABLE, 
	PRODUCT_QUANTITY NUMBER, 
	PRODUCT_DISCOUNT NUMBER, 
	PRODUCT_SELLINGPRICE NUMBER(10,2), 
	PRODUCT_SPECIFICATION VARCHAR2(200), 
	PRODUCT_SUPPLIER_ID VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT INFYRETAIL_PRODUCT_PK PRIMARY KEY (PRODUCT_ID) ENABLE, 
	 CONSTRAINT INFYRETAIL_PRODUCT_SUP_FK FOREIGN KEY (PRODUCT_SUPPLIER_ID)
	  REFERENCES  INFYRETAIL_USER (USER_ID) ENABLE
   );




INSERT INTO INFYRETAIL_ROLE VALUES ('A','ADMIN');

INSERT INTO INFYRETAIL_ROLE VALUES ('S','SUPPLIER');

INSERT INTO INFYRETAIL_ROLE VALUES ('C','CUSTOMER');




INSERT INTO INFYRETAIL_USER VALUES ('A101','INFY RETAIL','A','Admin@123','Admin@Imail.com',9876543210,'15-AUG-1947','#101A,HEBBAL INDUSTRIAL AREA,MYSURU,KARNATAKA,570027','M',NULL,'A');

INSERT INTO INFYRETAIL_USER VALUES ('S101','ABHI INFY','S','Abhi@123','Abhi@Imail.com',9876543211,'23-JAN-1992','#102A,ELECTRONIC CITY,BENGALURU,KARNATAKA,560100','M',NULL,'A');

INSERT INTO INFYRETAIL_USER VALUES ('C101','SALEEM INFY','C','Saleem@123','Saleem@Imail.com',9876543212,'22-JAN-1991','#103A,M CITY,CHENNAI,TAMILNADU,603002','M','GOLD','A');




INSERT INTO INFYRETAIL_PRODUCT  VALUES (1000,'IPHONE 6','MOBILE','APPLE',52599.00,5,10,54599.00,'COLOR:SPACE GREY,ROM:64 GB','S101');
INSERT INTO INFYRETAIL_PRODUCT  VALUES (1001,'LUMIA 930','MOBILE','NOKIA',25599.00,7,8,28599.00,'COLOR:BLACK,ROM:32 GB','S101');
INSERT INTO INFYRETAIL_PRODUCT  VALUES (1002,'ADIDAS RUNNINS SHOES','SPORT SHOES','ADIDAS',2499.00,10,5,2699.00,'IDEALFOR:MEN,OCCASION:SPORTS','S101');
INSERT INTO INFYRETAIL_PRODUCT  VALUES (1003,'ROUND NECK TSHIRT','TSHIRT','JOCKEY',399.00,6,5,499.00,'IDEALFOR:MEN,TYPE:ROUNDNECK,SIZE:MEDIUM','S101');

select PRODUCT_ID, PRODUCT_NAME , PRODUCT_CATEGORY, PRODUCT_BRAND ,PRODUCT_COST , PRODUCT_QUANTITY, PRODUCT_DISCOUNT , PRODUCT_SELLINGPRICE , PRODUCT_SPECIFICATION, PRODUCT_SUPPLIER_ID from INFYRETAIL_PRODUCT ;

select * from INFYRETAIL_PRODUCT;
select * from INFYRETAIL_USER;

COMMIT;